// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpqbUNBsuV-NNiTfkX0IJtdqNNVevpocg',
    appId: '1:752301943254:web:a5554bb0177f864f77dc77',
    messagingSenderId: '752301943254',
    projectId: 'feniks-9cda4',
    authDomain: 'feniks-9cda4.firebaseapp.com',
    storageBucket: 'feniks-9cda4.firebasestorage.app',
    measurementId: 'G-4332QN5SLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1uEPcOR95e_dNO7HQ2VAKIbTOqrg_YI',
    appId: '1:752301943254:android:44a202ade1681dfd77dc77',
    messagingSenderId: '752301943254',
    projectId: 'feniks-9cda4',
    storageBucket: 'feniks-9cda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlY5U3n-C2uN_hZXV2Ph4uTvf7OGb75bY',
    appId: '1:752301943254:ios:8451c750813515ec77dc77',
    messagingSenderId: '752301943254',
    projectId: 'feniks-9cda4',
    storageBucket: 'feniks-9cda4.firebasestorage.app',
    iosBundleId: 'com.example.feniksflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlY5U3n-C2uN_hZXV2Ph4uTvf7OGb75bY',
    appId: '1:752301943254:ios:8451c750813515ec77dc77',
    messagingSenderId: '752301943254',
    projectId: 'feniks-9cda4',
    storageBucket: 'feniks-9cda4.firebasestorage.app',
    iosBundleId: 'com.example.feniksflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpqbUNBsuV-NNiTfkX0IJtdqNNVevpocg',
    appId: '1:752301943254:web:1c65f238ddc8ceb277dc77',
    messagingSenderId: '752301943254',
    projectId: 'feniks-9cda4',
    authDomain: 'feniks-9cda4.firebaseapp.com',
    storageBucket: 'feniks-9cda4.firebasestorage.app',
    measurementId: 'G-X4DJ8VHZ3N',
  );
}
